spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: true
      initialization-fail-timeout: 1
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;MODE=MYSQL
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
