spring:
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: true
      initialization-fail-timeout: 1
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;MODE=MYSQL
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  kafka:
    admin:
      auto-create: true # Don't do this in production
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
